### ISSUE TITLE
3 - Criteria for investing  + 2 - In our portfolio

### ISSUE THREAD

**Issue by AntoineButeau** [Bloomberg-Beta/Manual#29]
Hi guys,

Firstly, thanks for doing this. Very helpful and transparent.
It would be great if you could do a mix of Criteria for investing + In our portfolio.
For example, for Newsle what was the rationale behind the investment and criterias they had.

Best,

**Comment by roybahat** [comment]
What a great request. Thought about it for a bit, and unfortunately this is something that we're unlikely to be able to do ever -- for a few reasons.
1. The reason to invest is often because of a fact (or factor) that's private information to the company, and so that information isn't always ours to share (and if you do it for one, you have to do it for all).
2. The criteria will continue to evolve over time, so a rationale for an investment when it was made may not be a match for our criteria at a later date when someone comes and checks out the site.
3. Different people will have different reasons for believing in a deal, so it's not like the fund has *one* rationale for any deal -- often times more than one of us is enthusiastic for different reasons.

**Comment by AntoineButeau** [comment]
@roybahat Thanks for considering and for the great answer. ✌️
